on: [push]

jobs:
  doc_validator_job:
    runs-on: ubuntu-latest
    name: A job to test doc-validator
    steps:
      - uses: actions/setup-node@v2
          with:
            node-version: '12'
      - run: npm install
      - name: run doc-validator
        uses: amitmiran137/doc-validator-action@v1.1
        with:
          markdown: './resources/bad_example'
      - name: fail step if parse was successful
        run: exit 1
        if: ${{ success() }}
